---
server:
  port: 9091

logging:
  level:
    org.springframework.web: ERROR
    vn.com: DEBUG
  file: /opt/lsn/log/bo-server.log

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: lsn

jwt:
  header: Authorization
